FROM node:14.15.3-alpine as build-stage
RUN npm install -g @angular/cli@9.1.4
# RUN npm install -g node-sass

WORKDIR /app
COPY ./ /app/
RUN npm install
# RUN node-sass -w scss-files -o css-files
#RUN sed '5,5 d' ./node_modules/ts-xlsx/lib/main.d.ts > ./node_modules/ts-xlsx/lib/main.d.ts
#RUN echo "export { readFile, read, utils, write, Properties, ParsingOptions, WorkBook, WorkSheet, CellObject, StreamUtils } from \"xlsx\";" >> ./node_modules/ts-xlsx/lib/main.d.ts
RUN ng build  --prod --base-href "/" #--deploy-url "https://redenlacecnf.redenlace.com.bo/"

FROM httpd:latest
RUN rm /usr/local/apache2/htdocs/index.html

RUN sed -i \
  's/#LoadModule rewrite_module modules\/mod_rewrite.so/LoadModule rewrite_module modules\/mod_rewrite.so/g' \
  /usr/local/apache2/conf/httpd.conf

# Append to the published directory, that we want to rewrite any request that is not an actual file
# to the index.html page.
RUN sed -i '/<Directory "\/usr\/local\/apache2\/htdocs">/a### Rewrite rule was written from the Dockerfile when building the image ###\n\
  DirectoryIndex index.html\n\
  RewriteEngine on\n\
  RewriteCond %{REQUEST_FILENAME} -s [OR]\n\
  RewriteCond %{REQUEST_FILENAME} -d\n\
  RewriteRule ^.*$ - [NC,L]\n\
  RewriteRule ^(.*) index.html [NC,L]\n' \
  /usr/local/apache2/conf/httpd.conf

# Comment out the default config that handles requests to /.htaccess and /.ht* with a special error message,
# Angular will handle all routing
RUN sed -i '/<Files "\.ht\*">/,/<\/Files>/c# This was commented out from the Dockerfile\n# <Files ".ht*">\n#     Require all denied\n# <\/Files>' \
  /usr/local/apache2/conf/httpd.conf

RUN sed -i '288s/.*/    Options -Indexes\n/' /usr/local/apache2/conf/httpd.conf

RUN sed -i '/Group daemon/a### Rewrite rule was written from the Dockerfile when building the image ###\n\
  <IfModule mod_headers.c>\n\
  Header set X-XSS-Protection "1; mode=block"\n\
  Header always append X-Frame-Options SAMEORIGIN\n\
  Header set X-Content-Type-Options nosniff\n\
  </IfModule>\n' \
  /usr/local/apache2/conf/httpd.conf

COPY --from=build-stage /app/dist/babylon/ /usr/local/apache2/htdocs/

EXPOSE 80
CMD ["httpd", "-D", "FOREGROUND"]
